### ISSUE TITLE
请教一个问题：Cannot run program "pandoc"

### ISSUE THREAD

**Issue by laotianye31** [chenhongen/jtex#1]
您好，请问您的这一段代码是什么意思
```java
CmdUtil.exec("pandoc " + path + File.separator + "rebey.tex -o " + path + File.separator + "tex.doc --latex-engine=xelatex -V mainfont=\"SimSun\"");
```

我执行的时候报错
```
java.io.IOException: Cannot run program "pandoc": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at org.usajusaj.jtex.util.CmdUtil.exec(CmdUtil.java:18)
	at org.usajusaj.jtex.samples.Test.main(Test.java:78)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
```

**Comment by chenhongen** [comment]
你需要先安装[pandoc](http://www.pandoc.org/)。
